service: sls

frameworkVersion: '3'

	
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-west-2

functions:
  createPet:
    handler: api/pets.create
    memorySize: 128
    description: create new pet information
    events:
      - http: 
          path: pets
          method: post