service: dynamodb-crud-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.petsTableName}

  
custom:
  petsTableName: pets-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function

resources:
  Resources:
    PetsTable:
      Type: AWS::DynamoDB::Table
      properties:
        TableName: ${self:custom.petsTableName}
        AttributeDefinitions:
          - AttributeName: petsId
            AttributeType: S
        
        KeySchema:
          - AttributeName: petsId
            KeyType: HASH
        
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
             